name: Actions Workflow

on:
#  push:
  repository_dispatch:
    types: build

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1
      - name: List after checkout
        run: |
          pwd
          ls -al
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "Token = ${{ github.token }}"
      - name: Simple JS action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Pepe
      - name: Log Greeting output
        run: echo "Pepe ${{ steps.greet.outputs.time }}"