name: Container

on: [pull_request]

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: node:14.15.0-alpine3.10
    steps:
      - name: "Log Node Version"
        run: |
          node -v
          cat /etc/os-release