name: matrix

on: [push]


jobs:
  node-version:
    runs-on: ubuntu-latest
    steps:
      - name: Log Node version before
        run: |
          node -v
          npm -v
      - name: use setup-node
        uses: actions/setup-node@v1
        with:
          node-version: 6
      - name: Log Node version after
        run: |
          node -v
          npm -v