name: Shell Commands

#on: [push]
on: [pull_request]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multiline cmds
        run: |
          node -v
          npm -v
      - name: python cmd
        shell: python
        run: |
            import platform
            print(platform.processor())
  run-windows-commands:
    runs-on: windows-latest
    needs: [run-shell-commands]
    steps:
      - name: print dir PS
        run: Get-Location
      - name: print dir BASH
        run: pwd
        shell: bash
      - name: python cmd
        shell: python
        run: |
            import platform
            print(platform.processor())